#!/usr/bin/env python3
"""Extract paint-booth transient metric time series from foamToVTK outputs.

The script expects an OpenFOAM case with `VTK/<case>_<time>/internal.vtu`
folders generated by `foamToVTK` (all times or selected times). It reuses the
metric primitives from `postprocess_paint_booth_plenum_metrics.py` and writes a
compact CSV/JSON time series plus first-order response diagnostics.
"""
from __future__ import annotations

import argparse
import csv
import json
import math
from pathlib import Path
from typing import Any

import pyvista as pv

from postprocess_paint_booth_plenum_metrics import (
    DEFAULT_REGIONS,
    load_case_metadata,
    patch_flow_metrics,
    region_metrics,
)


def vtk_series_time_map(case_dir: Path) -> dict[str, float]:
    """Return mapping from foamToVTK directory name to physical OpenFOAM time.

    OpenFOAM v1912 foamToVTK directory suffixes are write indices, not always
    physical times. The `.vtm.series` file is the authoritative mapping.
    """
    series_path = case_dir / "VTK" / f"{case_dir.name}.vtm.series"
    if not series_path.exists():
        return {}
    data = json.loads(series_path.read_text())
    mapping: dict[str, float] = {}
    for item in data.get("files", []):
        name = item.get("name", "")
        if name.endswith(".vtm"):
            mapping[name[:-4]] = float(item["time"])
    return mapping


def parse_time_from_vtk_dir(path: Path, case_name: str, series_map: dict[str, float]) -> float:
    if path.name in series_map:
        return series_map[path.name]
    prefix = f"{case_name}_"
    token = path.name[len(prefix):] if path.name.startswith(prefix) else path.name.rsplit("_", 1)[-1]
    try:
        return float(token)
    except ValueError as exc:
        raise ValueError(f"Cannot parse time from VTK directory name: {path.name}") from exc


def vtk_time_dirs(case_dir: Path) -> list[tuple[float, Path]]:
    vtk_root = case_dir / "VTK"
    if not vtk_root.exists():
        raise FileNotFoundError(f"VTK directory not found: {vtk_root}")
    series_map = vtk_series_time_map(case_dir)
    out: list[tuple[float, Path]] = []
    for p in vtk_root.iterdir():
        if p.is_dir() and (p / "internal.vtu").exists() and (p / "boundary").exists():
            out.append((parse_time_from_vtk_dir(p, case_dir.name, series_map), p))
    if not out:
        raise FileNotFoundError(f"No VTK time directories found under {vtk_root}")
    return sorted(out, key=lambda item: item[0])


def metric_row(case_dir: Path, time_s: float, vtk_dir: Path) -> dict[str, Any]:
    mesh = pv.read(vtk_dir / "internal.vtu")
    regions = region_metrics(mesh, DEFAULT_REGIONS)
    boundary_dir = vtk_dir / "boundary"
    supply = patch_flow_metrics(boundary_dir, "supplyInlet")
    floor = patch_flow_metrics(boundary_dir, "floorExhaust")
    supply_in = supply.get("inflow_m3s", 0.0)
    floor_out = floor.get("outflow_m3s", 0.0)
    above_p = regions["pressure_above_filter"].get("p", {}).get("mean")
    below_p = regions["pressure_below_filter"].get("p", {}).get("mean")
    pressure_drop = None if above_p is None or below_p is None else float(above_p - below_p)

    return {
        "time_s": float(time_s),
        "vtk_dir": str(vtk_dir),
        "supply_inflow_m3s": float(supply_in),
        "floor_outflow_m3s": float(floor_out),
        "net_out_minus_in_m3s": float(floor_out - supply_in),
        "relative_imbalance_out_minus_in": float((floor_out - supply_in) / max(abs(supply_in), 1e-12)),
        "work_zone_Uz_mean": regions["work_zone"]["Uz"]["mean"],
        "near_car_Uz_mean": regions["near_car"]["Uz"]["mean"],
        "near_car_reverse_fraction_Uz_positive": regions["near_car"]["downdraft_uniformity"]["reverse_flow_fraction_Uz_positive"],
        "filter_layer_panel_Uz_mean": regions["filter_layer_panel"]["Uz"]["mean"],
        "filter_pressure_drop_proxy_m2_per_s2": pressure_drop,
    }


def interpolate_crossing_time(rows: list[dict[str, Any]], key: str, fraction: float) -> float | None:
    if len(rows) < 2:
        return None
    y0 = rows[0][key]
    yf = rows[-1][key]
    denom = yf - y0
    if abs(denom) < 1e-15:
        return None
    prev_t = rows[0]["time_s"]
    prev_r = 0.0
    for row in rows[1:]:
        t = row["time_s"]
        r = (row[key] - y0) / denom
        if (prev_r <= fraction <= r) or (prev_r >= fraction >= r):
            if abs(r - prev_r) < 1e-15:
                return float(t)
            w = (fraction - prev_r) / (r - prev_r)
            return float(prev_t + w * (t - prev_t))
        prev_t, prev_r = t, r
    return None


def settling_time(rows: list[dict[str, Any]], key: str, epsilon: float) -> float | None:
    if len(rows) < 2:
        return None
    y0 = rows[0][key]
    yf = rows[-1][key]
    scale = abs(yf - y0)
    if scale < 1e-15:
        return None
    ok = [abs(row[key] - yf) <= epsilon * scale for row in rows]
    for i, row in enumerate(rows):
        if all(ok[i:]):
            return float(row["time_s"])
    return None


def response_summary(rows: list[dict[str, Any]], keys: list[str]) -> dict[str, Any]:
    out: dict[str, Any] = {}
    for key in keys:
        values = [row[key] for row in rows]
        y0 = values[0]
        yf = values[-1]
        delta = yf - y0
        normalized = [(v - y0) / delta for v in values] if abs(delta) >= 1e-15 else [0.0 for _ in values]
        out[key] = {
            "initial": float(y0),
            "final_observed": float(yf),
            "delta_observed": float(delta),
            "t63_s": interpolate_crossing_time(rows, key, 0.6321205588),
            "t90_s": interpolate_crossing_time(rows, key, 0.90),
            "t95_s": interpolate_crossing_time(rows, key, 0.95),
            "settling_time_10pct_s": settling_time(rows, key, 0.10),
            "settling_time_5pct_s": settling_time(rows, key, 0.05),
            "max_abs_deviation_from_final": float(max(abs(v - yf) for v in values)),
            "overshoot_beyond_final_fraction": float(max(0.0, max(normalized) - 1.0)),
            "undershoot_before_initial_fraction": float(max(0.0, -min(normalized))),
        }
    return out


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("case_dir", type=Path)
    parser.add_argument("--output-prefix", type=Path, default=None)
    args = parser.parse_args()

    case_dir = args.case_dir.resolve()
    prefix = args.output_prefix or (case_dir / "post_transient_metrics_timeseries")

    rows = [metric_row(case_dir, time_s, vtk_dir) for time_s, vtk_dir in vtk_time_dirs(case_dir)]
    keys = [
        "supply_inflow_m3s",
        "floor_outflow_m3s",
        "work_zone_Uz_mean",
        "near_car_Uz_mean",
        "near_car_reverse_fraction_Uz_positive",
        "filter_layer_panel_Uz_mean",
        "filter_pressure_drop_proxy_m2_per_s2",
    ]
    summary = {
        "case_dir": str(case_dir),
        "metadata": load_case_metadata(case_dir),
        "n_times": len(rows),
        "time_start_s": rows[0]["time_s"],
        "time_end_s": rows[-1]["time_s"],
        "metric_keys": keys,
        "response_summary": response_summary(rows, keys),
    }

    csv_path = prefix.with_suffix(".csv")
    json_path = prefix.with_suffix(".json")
    summary_path = Path(str(prefix) + "_summary.json")

    with csv_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)
    json_path.write_text(json.dumps(rows, indent=2), encoding="utf-8")
    summary_path.write_text(json.dumps(summary, indent=2), encoding="utf-8")

    print(json.dumps(summary, indent=2))
    print(f"Wrote {csv_path}")
    print(f"Wrote {json_path}")
    print(f"Wrote {summary_path}")


if __name__ == "__main__":
    main()
